baseURL = "https://www.jonathanschwarzhaupt.net/"
languageCode = "en-us"
title = "Jonathan Schwarzhaupt"
theme = "hugo-PaperModX"
enableEmoji = true
pygmentsUseClasses = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[minify]
disableXML = true
minifyOutput = true

[taxonomies]
tag = "tags"

[pagination]
pagerSize = 5

[params]
env = "production"
description = "Engineering Data Solutions"
author = "Jonathan Schwarzhaupt"
defaultTheme = "auto"
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true
TocSide = "left"

[params.homeInfoParams]
Title = "Engineering Data Solutions"
Content = """
👋 Welcome to my page!

I am Jonathan, a Data Engineer based in Munich, Germany.
Here I share little snippets of things that I learn, find interesting, or worth discussing.

I will post mostly about topics that relate to the practice of data engineering. These might be centered around Microsoft Azure, Linux, and open source technology such as Airflow, DuckDB, or dlt. I also plan to publish posts around data governance, management, and strategy as I firmly believe that data (engineering) projects are most successful, if they are truly part of an organization's broader business strategy.

At some point you'll find some of my personal projects here too (once those are ready to share 😉) - from a fun facts CLI and a recipe management web server written in Go to a data analytics platform for my personal finances.

You can find my socials and recent posts below and check the "*[About]( {{< ref "/about/" >}} )*" page in case you'd like to know more about me!
"""

[[params.socialIcons]]
name = "github"
title = "View my GitHub"
url = "https://github.com/jonathanschwarzhaupt/"

[[params.socialIcons]]
name = "linkedin"
title = "View my LinkedIn"
url = "https://www.linkedin.com/in/jonathanschwarzhaupt/"

[[menu.main]]
identifier = "About"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "Posts"
name = "Posts"
weight = 10
url = "/posts/"

[[menu.main]]
identifier = "Contact"
name = "Contact"
weight = 10
url = "/contact/"

[[menu.main]]
identifier = "Tags"
name = "Tags"
weight = 10
url = "/tags/"

[[menu.main]]
identifier = "Search"
name = "Search"
weight = 10
url = "/search/"
